import React from 'react';

const FairnessPage: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto bg-white dark:bg-[#1e293b] p-8 rounded-xl border border-slate-200 dark:border-slate-800">
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">Provably Fair</h1>
            
            <div className="space-y-6 text-slate-600 dark:text-slate-300 leading-relaxed">
                <p>At RewardGrip.com, we believe in complete transparency. Our game systems (Boxes and Battles) utilize a Provably Fair system that allows you to verify every result.</p>

                <section>
                    <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">How it works</h2>
                    <p>The result of every game is determined by a combination of three inputs:</p>
                    <ul className="list-disc list-inside mt-2 pl-4 space-y-1">
                        <li><strong>Server Seed:</strong> A random string generated by our server.</li>
                        <li><strong>Client Seed:</strong> A random string provided by your browser (which you can change).</li>
                        <li><strong>Nonce:</strong> A number that increments with every game you play.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">Verification</h2>
                    <p>Before you start playing, we show you the hashed version of the Server Seed. Since hash functions are irreversible, we cannot change the seed after showing you the hash without the hash changing as well.</p>
                    <p className="mt-2">Once a game is finished, we reveal the unhashed Server Seed. You can then use an online tool or our verification form to hash the revealed seed and check if it matches the one we showed you before the game.</p>
                </section>

                <div className="bg-slate-100 dark:bg-[#141c2f] p-6 rounded-lg mt-6">
                    <h3 className="font-bold text-slate-900 dark:text-white mb-4">Verify a Game</h3>
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-slate-500 mb-1">Server Seed</label>
                            <input type="text" className="w-full bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-600 rounded px-3 py-2" placeholder="Enter server seed" />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-500 mb-1">Client Seed</label>
                            <input type="text" className="w-full bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-600 rounded px-3 py-2" placeholder="Enter client seed" />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-500 mb-1">Nonce</label>
                            <input type="number" className="w-full bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-600 rounded px-3 py-2" placeholder="0" />
                        </div>
                        <button className="bg-green-500 text-white px-4 py-2 rounded font-bold hover:bg-green-600">Verify</button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default FairnessPage;